#! /bin/bash

is_installed()
{
	brew ls --versions $1 > /dev/null;
}

install()
{
	if ! is_installed $1; then
		brew install $1
	fi
}

for dependency in $(cat recipe.json | jq .dependencies | jq -r .[]); do
	install $dependency
done
